### ISSUE TITLE
Question: own fonts

### ISSUE THREAD

**Issue by HWHardsoft** [nopnop2002/Raspberry-ili9340spi#19]
Hi,
thx for this great work. I'm using your library with an ili9341 tft and Pi Zero. Is there a chance to use own fonts with your code? How can I convert other fonts?

Thx and Br

Hartmut

**Comment by nopnop2002** [comment]
Hello.

Yes.

You can add your original font file.

I updated the README.MD and added a description about the font.

**Comment by HWHardsoft** [comment]
Thx for the ultra fast reply :-)
