### ISSUE TITLE
www.airspayce.com link 404

### ISSUE THREAD

**Issue by Liquidlogic1** [nopnop2002/Raspberry-ili9340spi#20]
Under 'Build using bcm2835 library'
the 'wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.56.tar.gz' returns 404 and will not complete the install.

**Comment by vanvught** [comment]
Use  wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.64.tar.gz
