### ISSUE TITLE
Direct control of the LED pin 8

### ISSUE THREAD

**Issue by Aquidneck** [nopnop2002/Raspberry-ili9340spi#25]
Objective is to control the LED to on/off.  I used the following code additions, with the appropriate additions to the .h file:

#define LED 18  //  GPIO pin 12
void LED_on(void) {
  bcm2835_gpio_fsel(LED,BCM2835_GPIO_FSEL_OUTP); // LED
  bcm2835_gpio_write(LED, HIGH);
}
 
void LED_off(void) {
  bcm2835_gpio_fsel(LED,BCM2835_GPIO_FSEL_OUTP); // LED
  bcm2835_gpio_write(LED, LOW);
}

Those changes compile successfully, along with the addition of the calls to turn the LED on at the start of the main segment in demo.c and at the end to turn the LED off.  I plead guilty to little or no knowledge of the BCM2834, so I just used your existing code for the RES function.  The result is now a segmentation fault with those changes in place, whereas it runs normally with the original code.

Any suggestions??

**Comment by nopnop2002** [comment]
Use RPiGPIOPin number

https://www.airspayce.com/mikem/bcm2835/group__constants.html#ga63c029bd6500167152db4e57736d0939

Version 2, Pin P1-12 is Version 2, Pin P1-12
‘‘‘
RPI_V2_GPIO_P1_12=18
‘‘‘
