### ISSUE TITLE
PEN IRQ not responding 

### ISSUE THREAD

**Issue by d0n13** [nopnop2002/Raspberry-ili9340spi#26]
Values are not updating with touch. When I remove pin 14 (IRQ) on display side the values update but only X. Y seems to be stuck close to 32768 so all bits on likely.
Is it likely I have a fault touch panel or chip? Wired as per your example setup. 

The screen works ok though.

**Comment by nopnop2002** [comment]
There is a TFT equipped with HR2046.
XPT2046 and HR2046 are very similar. But HR2046 does not work properly.

**Comment by d0n13** [comment]
Yea. I checked that. The chip is a xpt2046

**Comment by nopnop2002** [comment]
I would like to see this result.

```
cc -o xpt xpt.c xpt2046.c -lbcm2835   
sudo ./xpt
```

**Comment by d0n13** [comment]
There is no output until I pull out pin 14 (IRQ) to force it low. They I get the output below. I compiled with the debug flag on.

Put a scope on pin 14 too but it doesn't do anything when I touch screen. It just stays at 3.3v.

```
$ sudo ./xpt
rbuf[0]=00 rbuf[1]=00 rbuf[2]=00
rbuf[0]=00 rbuf[1]=7f rbuf[2]=f8
touch !! x=    0 y= 2047rbuf[0]=00 rbuf[1]=47 rbuf[2]=a8
rbuf[0]=00 rbuf[1]=7f rbuf[2]=f8
touch !! x= 1146 y= 2047rbuf[0]=00 rbuf[1]=5a rbuf[2]=a0
rbuf[0]=00 rbuf[1]=76 rbuf[2]=30
```

**Comment by d0n13** [comment]
![C090A364-9960-4659-8DE6-A7EB7294A67D](https://user-images.githubusercontent.com/5494992/186948492-706b5d8b-6d26-490a-be2e-2714defae2b3.jpeg)

**Comment by nopnop2002** [comment]
>There is no output until I pull out pin 14 (IRQ) to force it low.

Soldering with XPT2046 may be incomplete.

**Comment by d0n13** [comment]
> XPT2046 soldering may be incomplete.

Looks OK. It could be a faulty chip too. I'll take a chance and get another one and see how it goes.
