### ISSUE TITLE
SD card

### ISSUE THREAD

**Issue by PoeticSwam** [nopnop2002/Raspberry-ili9340spi#27]
Is there a way to display images from the built in SD card slot?

**Comment by nopnop2002** [comment]
https://ralimtek.com/posts/2016/2016-12-10-raspberry_pi_secondary_sd_card/#spi

**Comment by PoeticSwam** [comment]
No but like if the lcd has a built in SD slot, can I load images to the screen using this library?

**Comment by nopnop2002** [comment]
built in SD slot is same as external SD card reader
