### ISSUE TITLE
Display image

### ISSUE THREAD

**Issue by PoeticSwam** [nopnop2002/Raspberry-ili9340spi#29]
How would I display a locally saved image (.bmp for example) to the display. I'm running it over software spi of wiringPi.

**Comment by nopnop2002** [comment]
Try latest.

![ili9340-PNG](https://user-images.githubusercontent.com/6020549/232972373-401f78e2-4482-4480-bb06-fd5a6743ef22.JPG)
![ili9340-JPEG](https://user-images.githubusercontent.com/6020549/232972375-e7a3d2a4-0dcb-46e5-8f05-c3314e477646.JPG)

**Comment by PoeticSwam** [comment]
Thank you :)
